# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/ .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@172.17.0.1:5433/sqlmodeltest
    # depends_on:
    #   - db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
